version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
         name: install packages
         command: sudo apt-get install -y pv sshpass
      - run: chmod 775 script
      - run: ./script.sh
