version: 2
jobs:
  build:
    machine: true
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
         name: install packages
         command: sudo apt-get install -y pv wput
      - run: chmod 775 script.sh
      - run: ./script.sh
