version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
         name: Install packages
         command: sudo apt-get install -y pv wput
      - run: chmod 775 script.sh
      - run: ./script.sh

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build 
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * */14"
          filters:
            branches:
              only: stable

    jobs:
      - build
