version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
         name: install packages
         command: sudo apt-get update -qq ; sudo apt-get install -y pv wput
      - run: chmod 775 script.sh
      - run: ./script.sh
